apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: truenas-https
  namespace: monitoring
spec:
  jobName: truenas-probe
  vmProberSpec:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
    path: /probe
    scheme: http
  module: https_truenas
  targets:
    staticConfig:
      targets:
        - "https://172.16.10.19"
      labels:
        instance: truenas
  interval: 60s
  scrapeTimeout: 15s
