apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex
  namespace: plex
  annotations:
    internal-dns/target: "172.16.100.250"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: cilium-gateway-internal
      namespace: kube-system
      sectionName: https-lex-la
  hostnames:
    - plex.lex.la
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            remove:
              - X-Forwarded-For
              - X-Real-IP
              - X-Envoy-External-Address
      backendRefs:
        - group: ""
          kind: Service
          name: plex-plex-media-server
          port: 32400
          weight: 1
