apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex
  namespace: plex
  annotations:
    internal-dns/target: "172.16.100.250"
spec:
  parentRefs:
    - name: cilium-gateway-internal
      namespace: kube-system
      sectionName: https-lex-la
  hostnames:
    - plex.lex.la
  rules:
    - backendRefs:
        - name: plex-plex-media-server
          port: 32400
