apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transmission-bot-secrets
  namespace: transmission-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: transmission-bot-secrets
    creationPolicy: Owner
  data:
    - secretKey: TB_TELEGRAM_TOKEN
      remoteRef:
        key: secret/data/transmission/bot
        property: TB_TELEGRAM_TOKEN
