apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: me-site-onion-secret
  namespace: me-site
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: me-site-onion-secret
    creationPolicy: Owner
  data:
    - secretKey: onionAddress
      remoteRef:
        key: secret/data/tor/onion-keys
        property: onionAddress
    - secretKey: privateKeyFile
      remoteRef:
        key: secret/data/tor/onion-keys
        property: privateKeyFile
    - secretKey: publicKeyFile
      remoteRef:
        key: secret/data/tor/onion-keys
        property: publicKeyFile
