apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
spec:
  serviceSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: NotIn
        values:
          - papermc
  nodeSelector:
    matchLabels: {}
  interfaces:
    - ^eth[0-9]+
    - ^en[ospx][0-9]+
  externalIPs: true
  loadBalancerIPs: true
