apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-access
  namespace: kube-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      namespace: argocd
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: argocd
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: homepage
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: longhorn-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: monitoring
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: security
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: transmission-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: estimator
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: me-site
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: paper
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: wish-operator
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: job-countdown
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: homebridge
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: homeassistant
  to:
    - group: ""
      kind: Service
      name: "*"
