apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba-users
  namespace: samba
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: samba-users
    creationPolicy: Owner
  data:
    - secretKey: users.json
      remoteRef:
        key: secret/data/samba/users
        property: config
