apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: job-countdown
  annotations: {}
spec:
  parentRefs:
    - name: cloudflare-tunnel
      namespace: cloudflare-tunnel-system
  hostnames:
    - job.lex.la
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: job-countdown
          port: 8080
