apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  jetstream:
    version: latest
    replicas: 1
    persistence:
      storageClassName: longhorn
      accessMode: ReadWriteOnce
      volumeSize: 1Gi
    streamConfig: |
      maxMsgs: 1000000
      maxAge: 72h
      maxBytes: 1GB
      replicas: 1
      duplicates: 300s
      retention: 0
      discard: 0
