apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar
  namespace: argo-events
spec:
  calendar:
    system-upgrade-weekly:
      schedule: "0 5 * * 5"
      timezone: "Asia/Tbilisi"
      exclusionDates: []
      metadata:
        event-type: system-upgrade
        schedule: weekly
