apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  jetstream:
    version: latest
    replicas: 1
    persistence:
      storageClassName: longhorn
      accessMode: ReadWriteOnce
      volumeSize: 1Gi
