apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: system-upgrade
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: calendar-event
      eventSourceName: calendar
      eventName: system-upgrade-weekly
  triggers:
    - template:
        name: system-upgrade-workflow
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: system-upgrade-
                namespace: argo-events
                labels:
                  workflows.argoproj.io/workflow-template: system-upgrade
              spec:
                workflowTemplateRef:
                  name: system-upgrade
          parameters:
            - src:
                dependencyName: calendar-event
                dataKey: eventTime
              dest: spec.arguments.parameters.0.value
