apiVersion: wishlist.k8s.lex.la/v1alpha1
kind: Wish
metadata:
  name: meross-air-purifier
  namespace: wish-operator
spec:
  quantity: 2
  title: "Meross Smart Air Purifier MAP100"
  imageURL: "https://static-file.meross.com/uploads/1628134416347_4bc5cd22.jpg"
  officialURL: "https://www.meross.com/en-gc/smart-air-purifier/homekit-air-purifier/112"
  purchaseURLs:
    - "https://shop.meross.com/products/meross-smart-air-purifier"
    - "https://www.amazon.com/meross-Purifier-Assistant-SmartThings-Allergies/dp/B098DWRLBF"
  msrp: "$ 100"
  tags:
    - electronics
    - smarthome
    - homekit
  contextTags:
    - any-occasion
  description: "Smart Wi-Fi air purifier with H13 HEPA filter. Supports HomeKit, Alexa, Google Home. Covers up to 207 sq ft, 24dB quiet operation."
  priority: 4
