apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge-config-template
  namespace: homebridge
data:
  config.json: |
    {
      "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
      },
      "platforms": [
        {
          "platform": "MiHumidifier",
          "devices": [
            {
              "name": "Office Humidifier",
              "address": "172.16.10.27",
              "token": "${OFFICE_TOKEN}",
              "model": "zhimi.humidifier.ca4",
              "updateInterval": 30,
              "autoSwitchToHumidityMode": true,
              "ledBulb": {
                "enabled": true,
                "name": "Office Humidifier LED"
              },
              "buzzerSwitch": {
                "enabled": true,
                "name": "Office Humidifier Buzzer"
              },
              "temperatureSensor": {
                "enabled": true,
                "name": "Office Temperature"
              },
              "humiditySensor": {
                "enabled": true,
                "name": "Office Humidity"
              },
              "cleanModeSwitch": {
                "enabled": true,
                "name": "Office Humidifier Clean Mode"
              }
            },
            {
              "name": "Bedroom Humidifier",
              "address": "172.16.10.198",
              "token": "${BEDROOM_TOKEN}",
              "model": "zhimi.humidifier.ca4",
              "updateInterval": 30,
              "autoSwitchToHumidityMode": true,
              "ledBulb": {
                "enabled": true,
                "name": "Bedroom Humidifier LED"
              },
              "buzzerSwitch": {
                "enabled": true,
                "name": "Bedroom Humidifier Buzzer"
              },
              "temperatureSensor": {
                "enabled": true,
                "name": "Bedroom Temperature"
              },
              "humiditySensor": {
                "enabled": true,
                "name": "Bedroom Humidity"
              },
              "cleanModeSwitch": {
                "enabled": true,
                "name": "Bedroom Humidifier Clean Mode"
              }
            }
          ]
        }
      ]
    }
