apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebridge-tokens
  namespace: homebridge
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: homebridge-tokens
    creationPolicy: Owner
  data:
    - secretKey: OFFICE_TOKEN
      remoteRef:
        key: secret/data/homebridge
        property: office_token
    - secretKey: BEDROOM_TOKEN
      remoteRef:
        key: secret/data/homebridge
        property: bedroom_token
