apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-config
  namespace: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-remote
  resources:
    requests:
      storage: 1Gi
