apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
  data:
    - secretKey: HOMEPAGE_VAR_ARGOCD_KEY
      remoteRef:
        key: secret/data/homepage
        property: argocd_key
    - secretKey: HOMEPAGE_VAR_TRUENAS_KEY
      remoteRef:
        key: secret/data/homepage
        property: truenas_key
    - secretKey: HOMEPAGE_VAR_UNIFI_KEY
      remoteRef:
        key: secret/data/homepage
        property: unifi_key
