apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cloudflare-tunnel-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: secret/data/cloudflare/tunnel-credentials
        property: api-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/cloudflare/tunnel-token
        property: tunnel-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: awg-config
  namespace: cloudflare-tunnel-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: awg-config
    creationPolicy: Owner
  data:
    - secretKey: wg0.conf
      remoteRef:
        key: secret/data/cloudflare/awg-config
        property: wg0.conf
