apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
  namespace: transmission-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zfs-localpv
  resources:
    requests:
      storage: 10Ti
  volumeName: zfs-transmission
