apiVersion: v1
kind: Service
metadata:
  name: graphite-exporter-graphite
  namespace: monitoring
  labels:
    app.kubernetes.io/name: graphite-exporter
    app.kubernetes.io/instance: graphite-exporter
  annotations:
    internal-dns/hostname: graphite.home.lex.la
spec:
  type: LoadBalancer
  ports:
    - name: graphite-tcp
      port: 2003
      targetPort: graphite-tcp
      protocol: TCP
  selector:
    app.kubernetes.io/name: graphite-exporter
    app.kubernetes.io/instance: graphite-exporter
