apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-runner-pat
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: arc-runner-pat
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: secret/data/github/arc-runner-pat
        property: github_token
