apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-ci-token
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: argocd-ci-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/argocd/ci-token
        property: token
