repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: metallb
    url: https://metallb.github.io/metallb

releases:
  # https://github.com/metallb/metallb/tree/main/charts/metallb
  - name: metallb
    namespace: metallb-system
    installed: true
    chart: metallb/metallb
    values:
      - configInline:
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - 192.168.6.0/24
            - name: traefik
              protocol: layer2
              addresses:
                - 192.168.5.200/32

  # https://artifacthub.io/packages/helm/traefik/traefik
  #
  # Check this page before upgrade
  # https://doc.traefik.io/traefik/migration/v2/
  #
  - name: traefik
    namespace: traefik-system
    chart: traefik/traefik
    installed: true
    values:
      - service:
          annotations:
            metallb.universe.tf/address-pool: traefik
        additionalArguments:
          # Disable internal ssl check
          - "--serversTransport.insecureSkipVerify=true"
          # SSL for prod
          - "--certificatesresolvers.prodssl.acme.dnschallenge.provider=cloudflare"
          - "--certificatesresolvers.prodssl.acme.storage=/data/acme.json"
          - "--certificatesresolvers.prodssl.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
          - "--entrypoints.websecure.http.tls=true"
          - "--entrypoints.websecure.http.tls.certresolver=prodssl"
        globalArguments:
          - "--global.checknewversion"
        persistence:
          enabled: true
          storageClass: "longhorn-main"
        deployment:
          initContainers:
            # The "volume-permissions" init container is required if you run into permission issues.
            # Related issue: https://github.com/traefik/traefik/issues/6825
            - name: volume-permissions
              image: busybox:1.31.1
              command: ["sh", "-c", "chmod -Rv 600 /data/*"]
              volumeMounts:
                - name: data
                  mountPath: /data
        env:
          - name: CF_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cf-token
                key: token
        ports:
          web:
            redirectTo: websecure
