apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-api-key
  namespace: internal-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: unifi-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: secret/data/unifi/api-key
        property: api-key
