apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: security
data:
  users_database.yml: |
    users:
      lex:
        disabled: false
        displayname: "Aleksei Sviridkin"
        password: "$argon2id$v=19$m=65536,t=3,p=4$yFkBDZr9KXy85RLXvV9Zug$VR1VC2+FOL9Dq16jlCgXaO1NMvf35N0m0pRll5qhhxQ"
        email: "f@lex.la"
        groups:
          - admins
          - users
