apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-csi
  resources:
    requests:
      storage: 100Gi
